on: [push]
jobs:
  build:
  runs-on: ubuntu-latest
    steps:
      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1 # or @v1.x.x
        with:
          # Optional, if empty the latest bun version will be used
          # Examples: 0.0.77, 0.1.2, >=0.1, *
          bun-version: 1.0.2

          # Optional, default is 'Jarred-Sumner/bun-releases-for-updater'
          # Example: oven-sh/misc-test-builds
          bun-repo: 'oven-sh/bun'

          # Override bunfig.toml inners
          # Optional. JSON-formatted string as input
          # See: https://github.com/oven-sh/bun#bunfigtoml
          bun-config: '{"install": {"production": false}}'
          
          # Attach $BUN_INSTALL/install/cache to action/cache
          # Optional, defaults to false
          cache: true

          # actions/tool-cache provides a cache for the current job only
          # Use actions/cache to store the bun binary for the whole workflow
          # Optional, defaults to false
          cache-bin: true

          # Optional, default is process.platform
          # Examples: darwin, linux
          platform: 'linux'

          # Optional, default is process.arch
          # Examples: x64, arm64
          arch: 'x64'
          
          # Authenticated requests get a higher rate limit
          # Optional. Defaults to ${{ github.token }}
          token: 'gh-token'

      - name: Run script
        run: bun index.js